### ISSUE TITLE
Code feedback 💃

### ISSUE THREAD

**Issue by cydstumpel** [SanHont/look-and-feel-corporate-identity#1]
Hi Sander, 

Chill dat je in je css de code voor de veschillende onderdelen van je website gesplitst hebt met comments!

Verder zie ik dat je de css variables/custom properties in de root declareert, hartstikke netjes, je gebruikt alleen wel heeel veel kleuren!
Staan deze allemaal in de styleguide? Het is vaak ook leesbaarder en makkelijker om dingen aan te passen om variables (ook) een 'semantische' naam te geven; ik doe dit vaak als volgt:

```css
:root {
    --white: #FFF;
    --yellow: #FFD05F;
    --cyaan: #46BECD;
    --turquoise: #25AE93;
    --blue: #606EB3;
    --brown: #6A4955;
    --sand: #C9B5B2;
    --grey: #444444;
    --light-grey: #DDDDDD;
    --black: #000;
    --magenta-dark: #B9005F;
    --magenata-light: #E30059;
    --gradient-color-magenta: linear-gradient(332deg, #B9005F 0%, #E30059 100%);

	 /* Basics */
	--title-color: var(--magenta-dark);
	--text-color: var(--black);
	--text-block-background: var(--light);

    /* Side bar */
    --sidebar-color: var(--white);
    --sidebar-background: var(--magenta-dark);
    --sidebar-hover-background: var(--sand);
}
```

Als je dan bijvoorbeeld iets wil maken als een dark mode kan je de semantische property namen aan andere kleuren koppelen;
```css
@media (prefers-color-scheme: dark) {
	:root {
		 /* Basics */
		--title-color: var(--white);
		--text-color: var(--white);
		--text-block-background: var(--black);
	}
}
```
